name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run tests
    - name: Run tests
      run: |
        pytest

    # # 5. Set up Docker Buildx (for building Docker images)
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # # 6. Build Docker image
    # - name: Build Docker Image
    #   run: |
    #     docker build -t your-dockerhub-username/flask-house-prices-app:latest .